- hosts: on_premise_hosts
  tasks:
  - name: Check if SSH MaxStartups is configured or not
    shell: grep "^MaxStartups" /etc/ssh/sshd_config
    failed_when: false
    changed_when: false
    register: sshd_maxstartups_check
  - name: Fail if SSH MaxStartups is not configured correctly
    fail:
      msg: "Please configure SSH MaxStartups correctly"
    when: "'MaxStartups' not in sshd_maxstartups_check.stdout"